sudo: required

services:
  - docker

before_install:
  - docker build -t magiclost/docker-react -f Dockerfile.dev .

script:
  - docker run magiclost/docker-react npm test -- --coverage --watchAll=false

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: lizzygram
  on: master
