sudo: required

services:
  - docker

before_install:
  - docker build -t magiclost/docker-react -f Dockerfile.dev .

script:
  - docker run magiclost/docker-react npm test -- --coverage --watchAll=false
